export const RECEIVE_BANNERS = 'receive_banners'
export const RECEIVE_NEARCOUPONS = 'receive_nearcoupons'
export const RECEIVE_SHOPS = 'receive_shops'
export const RECEIVE_ADDRESS = 'receive_address'
export const RECEIVE_STORYS = 'receive_storys'
export const RECEIVE_ACTIVITYS = 'receive_activitys'